### ISSUE TITLE
Emulate cumulativity instead of using lists of universe levels?

### ISSUE THREAD

**Issue by effectfully** [Zekt/Type-Embellishment#1]
Hi, I've noticed you have these lists of explicit universe levels, which are always painful to deal with. Are you aware of the [trick](http://effectfully.blogspot.com/2016/07/cumu.html) that allows one to emulate cumulativity in Agda? I [used](https://github.com/effectfully/Generic/blob/c5ce2a5aaa67f609dd04f6e3d3fea96ca73b6b92/src/Generic/Core.agda#L11-L26) it in my own development of generics for Agda and I saw other people [using](https://github.com/flupe/generics/blob/f52ef0f0afdf1503d32bcda7aab0f48ba875381f/src/Generics/Desc.agda#L9-L19) it for the same purpose, so maybe it could be adapted in your case as well? As the latter link shows it's even simpler these days due to the addition of `Setω` to Agda.

**Comment by josh-hs-ko** [comment]
Hi, thanks for telling us about the trick! Presumably you’re talking about these lists of levels

https://github.com/Zekt/Type-Embellishment/blob/d8ca57673705b1823458e3ed327b34b054bae2bb/src/Generics/Safe/Description.agda#L10-L17

which we use to index our datatype descriptions. We did rediscover similar tricks, e.g.,

https://github.com/Zekt/Type-Embellishment/blob/d8ca57673705b1823458e3ed327b34b054bae2bb/src/Prelude/Level.agda#L32-L37

but for telescopes we just freely quantify over levels and put the datatype of telescopes in `Setω`,

https://github.com/Zekt/Type-Embellishment/blob/d8ca57673705b1823458e3ed327b34b054bae2bb/src/Generics/Safe/Telescope.agda#L12-L15

which looks simpler. We did the same thing with descriptions but later discovered that we need to expose more information about the structure of the descriptions via indices — i.e., those lists of levels — to compute various other stuff (not just the levels but also the lists themselves are actually important).

(And regarding cumulativity, doesn’t Agda already have a [cumulativity option](https://agda.readthedocs.io/en/latest/language/cumulativity.html)? We did think about turning on the option, and in fact feel that in general cumulativity may be a must, but I think we’ve solved most if not all of our universe level problems for now.)

**Comment by effectfully** [comment]
That makes sense, thanks!

> (And regarding cumulativity, doesn’t Agda already have a cumulativity option? We did think about turning on the option, and in fact feel that in general cumulativity may be a must, but I think we’ve solved most if not all of our universe level problems for now.)

(I've no idea, I stopped programming in Agda a few years ago)
