### ISSUE TITLE
Expressiveness of ornaments

### ISSUE THREAD

**Issue by effectfully** [Zekt/Type-Embellishment#2]
I've been looking into your development (cool stuff!), and I got a question: is your machinery expressive enough to represent an ornament from

```agda
  data D₁ : ℕ -> Set where
    C₁ : (∀ n -> D₁ (suc n)) -> D₁ 0
```

to

```agda
  data D₀ m : Fin (suc m) -> Set where
    C₀ : (∀ i -> D₀ m (suc i)) -> D₀ m zero
```

? It seems like [`RecO`](https://github.com/Zekt/Type-Embellishment/blob/d8ca57673705b1823458e3ed327b34b054bae2bb/src/Generics/Safe/Ornament.agda#L23) doesn't allow one to change the shape of a (possibly higher-order) recursive occurrence?

My [preferred](http://effectfully.blogspot.com/2016/04/descriptions.html) encoding of descriptions is very similar to yours (the main difference is that I use the same data type for both `ConD` and `RecD`, but there a couple minor differences too) and it allows for some beautiful [symmetry](http://effectfully.blogspot.com/2016/07/unbiased-ornaments.html) to ornaments, which makes it possible to change the shape not only of a constructor, but also of its recursive occurrences. I think in your system that would translate to two additional constructors of `RecO` symmetric to `Δ` and `∇` from `ConO`.

So what do you think, can your `RecO` be extended for some extra expressiveness or did I get things wrong here?

**Comment by josh-hs-ko** [comment]
You’re right! My first version did include `Δ` and `∇` in `RecO`, but there were some difficulties in subsequent developments (which I can’t remember now) so I simply [removed them](https://github.com/Zekt/Type-Embellishment/commit/084d888858165f2389bba161c57e3f640cdb9d37). It’s also in line with not allowing `ρ` to be modified in `ConD` (so there’s no fiddling with any kind of recursive occurrence). This version of ornaments is still somewhat rudimentary (and not so different from those in the early literature) and will definitely need extensions, but I want to identify a useful range of generic constructions before revising the design.

**Comment by effectfully** [comment]
Makes perfect sense, thanks!
